./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 10  >> res.txt
