./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrh4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnre3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrf2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Large/scpnrg4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp45.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp55.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp52.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp43.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp65.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp42.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp47.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp53.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp46.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp49.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp41.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp61.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp54.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp57.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp59.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp56.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp51.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp48.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp63.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp510.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe2.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp44.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp58.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp62.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpb5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc5.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp410.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scp64.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpe3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpa3.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpc1.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/OR-Small/scpd4.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-507.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4284.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2586.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-4872.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-516.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-582.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/Rail/rail-2536.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-13.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-11.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-12.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CLR/scpclr-10.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-08.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-09.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-06.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-07.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-11.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SCP-CYC/scpcyc-10.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/sac_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-L/javagc_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/Dune_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hsmgp_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/SQL_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/hipacc_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-M/BDBC_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/x264_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/BDBJ_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/Apache_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/SoftTest-S/LLVM_SCP.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-243.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-729.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-405.txt 1000 10  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 1  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 2  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 3  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 4  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 5  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 6  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 7  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 8  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 9  >> res.txt
./FastSC /home/wyy/benchmark/SCP/STS/sts-135.txt 1000 10  >> res.txt
